#!/bin/sh

cd ..

DATE=`date '+%Y_%m_%d_%H%M%S'`


#python train.py -i mydata/ntau_one --epochs=1
#python train.py --no-split -i mydata/ntau_one -ii mydata/ntau_one_validate --epochs=1 --batch-size=50
#python train.py -i mydata2/tau_5GeV_100k --timing-cut --use-charged-cluster-loss --output-dimension 4


#python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --thetaphi --cuda cuda:1 --epochs 50 --beta-track --force-track-alpha --batch-size 5 | tee log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi.log &



### output dimention tuning
outputD=5   # output coordinate dimension """""""+1"""""""
ncuda=0     #1  # 0 or 1
sample=ntau_10GeV_10      # ntau_10GeV_10   uds91   mix
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --thetaphi --cuda cuda:0 --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension 4 > log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD4.log
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --thetaphi --cuda cuda:0 --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension 5 > log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD5.log

## ntau
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD} > log/output_dimension/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log
## ntau skimmed
# python train.py -i /data/suehara/mldata/pfa/murata/skimmed/ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/skimmed/ntau_10GeV_10/validation --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD}_skimmed > log/output_dimension/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_skimmed.log
# python train.py -i /data/suehara/mldata/pfa/murata/skimmed/ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/skimmed/ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD}_skimmed > log/output_dimension/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_skimmed.log

## uds
# python train.py -i /data/suehara/gravnet_ilc/data/uds91/train -ii /data/suehara/gravnet_ilc/data/uds91/validation --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD} > log/output_dimension/tc_uds91_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log
## uds skimmed
# python train.py -i /data/suehara/mldata/pfa/murata/skimmed/uds91/train -ii /data/suehara/mldata/pfa/murata/skimmed/uds91/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD}_skimmed > log/output_dimension/tc_uds91_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_skimmed.log
# python train_multigpu.py -i /data/suehara/mldata/pfa/murata/skimmed/uds91/train -ii /data/suehara/mldata/pfa/murata/skimmed/uds91/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 40 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD}_skimmed > log/output_dimension/tc_uds91_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_skimmed.log

## mix sample
# python train.py -i /data/suehara/mldata/pfa/murata/mix_samples/train -ii /data/suehara/mldata/pfa/murata/mix_samples/validation --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 5 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD} > log/output_dimension/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log

### learning rate w/ output dimensions
lr=2e-5
lr=5e-5
lr=1e-4
lr=5e-4
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 10 --output-dimension ${outputD} --ckptdir checkpoint/output_dimensions/ckpts_gravnet_new02_${DATE}_outputD${outputD} --learning-rate ${lr} > log/output_dimension/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_lr${lr}_${DATE}.log


### energy regression
alphbeta=alpha      # alpha  betaE  alpha_ratio
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --regression-coefficinet 50 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_betaMSE.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
# python train_energyRegression_multigpu.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 100 --beta-track --force-track-alpha --batch-size 50 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
alphbeta=alpha_tracker_modifing
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --restart-period 30 --epochs-noLE -1 --momentum-amp > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log


## momentum
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --restart-period 30 --regression-coefficinet 0.5 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --restart-period 30 --regression-coefficinet 0.1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp --restart-period 30 --epochs-noLE -1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# alphbeta=alpha_tracker
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --restart-period 30 --epochs-noLE -1 --momentum-amp > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_absoluteMomentum.log

alphbeta=alpha
alphbeta=alpha_tracker
# alphbeta=alpha_tracker_sqrtdiv
# alphbeta=alpha_sqrtdiv
# alphbeta=alpha_tracker_modifing
# alphbeta=alpha_tracker_modifing_charged0
# alphbeta=alpha_tracker_modifing_all0


## full samples
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --momentum --momentum-amp --restart-period 30 --LE-track ${alphbeta}  --epochs-noLE -1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --momentum --momentum-amp --restart-period 500 --LE-track ${alphbeta} --LE-cluster sum --regression-coefficinet 0.1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --momentum --momentum-amp --LE-track ${alphbeta} --LE-cluster sum --regression-coefficinet 0.1 --ReduceLROnPlateau > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --momentum --momentum-amp --restart-period 30 --LE-track ${alphbeta} --LE-cluster sum --regression-coefficinet 0 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --momentum --momentum-amp --restart-period 30 --LE-track ${alphbeta} --regression-coefficinet 0.1 --LE-gradually > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --momentum --momentum-amp --restart-period 30 --LE-track ${alphbeta} --regression-coefficinet 0.1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --momentum --momentum-amp --restart-period 30 --LE-track ${alphbeta} --energy-branch --regression-coefficinet 0.1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
## reduced samples
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/ntau_lessSample/train -ii /data/suehara/mldata/pfa/murata/ntau_lessSample/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/reduced_samples/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --epochs-noLE -1 --mctpe > log/energy_regression/reduced_samples/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/ntau_lessSample/train -ii /data/suehara/mldata/pfa/murata/ntau_lessSample/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/reduced_samples/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --mctpe --regression-coefficinet 0.05 > log/energy_regression/reduced_samples/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/ntau_lessSample/train -ii /data/suehara/mldata/pfa/murata/ntau_lessSample/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/reduced_samples/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp > log/energy_regression/reduced_samples/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression_timemeasurement.py -i /data/suehara/mldata/pfa/murata/ntau_lessSample/train -ii /data/suehara/mldata/pfa/murata/ntau_lessSample/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/reduced_samples/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp



## test
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --epochs-noLE -1
# python train_energyRegression_timemeasurement.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --epochs-noLE -1 > test/calculationTime_${DATE}.log
# python -m cProfile -o shell/test.prof train_energyRegression.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 2 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --energy-regression-cluster --restart-period 30 --LE-track ${alphbeta} --LE-cluster sum --momentum --momentum-amp #> test/grad_${DATE}.log
# python -m cProfile -o shell/test.prof train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 2 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --restart-period 30 --LE-track ${alphbeta} --LE-cluster sum --momentum --momentum-amp >  test/grad_${DATE}.log
# python -m cProfile -o shell/no_cpuusage.prof train_energyRegression.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 2 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --energy-regression-cluster --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp
# python -m cProfile -o shell/no_cpuusage.prof train_energyRegression_timemeasurement.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 2 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --epochs-noLE -1
# python train_energyRegression_energybranch.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --LE-track ${alphbeta} --momentum --restart-period 30 --epochs-noLE -1 --momentum-amp --energy-branch > test/model_editing.log

## uds
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/uds91/train -ii /data/suehara/gravnet_ilc/data/uds91/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} > log/energy_regression/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
 ## momentum
sample=uds91      # ntau_10GeV_10   uds91   mix
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/uds91/train -ii /data/suehara/gravnet_ilc/data/uds91/validation --no-split --thetaphi --cuda cuda:0 --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum > log/energy_regression/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/tc_uds_91/train -ii /data/suehara/mldata/pfa/murata/tc_uds_91/validation --no-split --thetaphi --cuda cuda:0 --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --regression-coefficinet 0.1 > log/energy_regression/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2025_01_30_161918_outputD5/ckpt_499_1.pth.tar
alphbeta=alpha

ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2025_02_10_170311_outputD5/ckpt_499_1.pth.tar
alphbeta=alpha_tracker
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/tc_uds_91/train -ii /data/suehara/mldata/pfa/murata/tc_uds_91/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --LE-cluster sum --regression-coefficinet 0.1 --epochs-noLE -1 --epochs-nobeta -1 --model-ckpt ${ckpt} > log/energy_regression/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log


## test
# python train.py -i /data/suehara/mldata/pfa/murata/code_test_ntau/train -ii /data/suehara/mldata/pfa/murata/code_test_ntau/validation --no-split --thetaphi --cuda cuda:0 --epochs 500 --restart-period 30 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --lr-policy cosineReduce --nrestart-cosreduce 1 > test/test.log
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --LE-track ${alphbeta} --momentum #> test/learning_rate_.log
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint --energy-regression --LE-track ${alphbeta} --momentum
# python train.py -i /data/suehara/mldata/pfa/murata/code_test/train -ii /data/suehara/mldata/pfa/murata/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir test/checkpoint #> test/learning_rate_.log

## ntau_10to100GeV_10
sample=ntau_10to100GeV_10      # ntau_10GeV_10   uds91   mix
# python train_energyRegression.py -i /data/suehara/gravnet_ilc/data/ntau_10to100GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau_10to100GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} > log/energy_regression/tc_ntau_10to100GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/ntau_10to100GeV_10_lessSample/train -ii /data/suehara/mldata/pfa/murata/ntau_10to100GeV_10_lessSample/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 50 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} > log/energy_regression/tc_ntau_10to100GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/tc_ntau_10to100GeV_10/reduce/train -ii /data/suehara/mldata/pfa/murata/tc_ntau_10to100GeV_10/reduce/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 20 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --regression-coefficinet 0.1 --learning-rate 3e-5 > log/energy_regression/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2025_01_30_161918_outputD5/ckpt_499_1.pth.tar
alphbeta=alpha
# python train_energyRegression.py -i /data/suehara/mldata/pfa/murata/tc_ntau_10to100GeV_10/reduce/train -ii /data/suehara/mldata/pfa/murata/tc_ntau_10to100GeV_10/reduce/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 60 --beta-track --force-track-alpha --batch-size 10 --output-dimension 5 --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --restart-period 30 --LE-track ${alphbeta} --momentum --momentum-amp --regression-coefficinet 0.01 --epochs-noLE -1 --epochs-nobeta -1 --model-ckpt ${ckpt} > log/energy_regression/tc_${sample}_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log


## nnqq
outputD=5
ncuda=3
alphbeta=alpha_tracker_diff_log_perCluster
sumdis=sum_log_perCluster
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_nnqq/train -ii /data/suehara/mldata/pfa/murata/data/tc/tc_nnqq/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 1.25e-4 --lr-policy cosineReduce --clip-value 10 --l-beta-suppression --ddp > log/energy_regression/tc_nnqq_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
# alphbeta=weight
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_nnqq/train -ii /data/suehara/mldata/pfa/murata/data/tc/tc_nnqq/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp --qmin 0.2 --learning-rate 1e-4 --lr-policy cosineReduce --clip-value 10 --ddp > log/energy_regression/tc_nnqq_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
## nnqq brems cut
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/eventCut/tc_nnqq_brems/train -ii /data/suehara/mldata/pfa/murata/data/tc/eventCut/tc_nnqq_brems/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 1.25e-4 --lr-policy cosineReduce --clip-value 10 --ddp > log/energy_regression/tc_nnqq_brems_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
## nnqq brems cut (newest version! 2026/03/18)
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_nnqq_brems/train_lessSample -ii /data/suehara/mldata/pfa/murata/data/tc/tc_nnqq_brems/validation_lessSample --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 1.25e-4 --lr-policy cosineReduce --clip-value 10 --ddp --gpus 0,1,3,4 > log/energy_regression/tc_nnqq_brems_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
### 途中から
# ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2026_01_19_144839_outputD5/ckpt_141_1.pth.tar
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/eventCut/tc_nnqq_brems/train -ii /data/suehara/mldata/pfa/murata/data/tc/eventCut/tc_nnqq_brems/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 6e-5 --lr-policy cosineReduce --clip-value 10 --ddp --model-ckpt ${ckpt} --epochs-nobeta -1 --epochs-noLE -1 --nrestart-cosreduce 1 > log/energy_regression/tc_nnqq_brems_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log



## ntau 10GeV
alphbeta=alpha_tracker_diff_log_perCluster
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 50 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --energy-regression-weight --momentum --momentum-amp --qmin 0.2 --learning-rate 1e-4 --lr-policy cosineReduce --clip-value 10 --ddp > log/energy_regression/weighted_edep/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log

## neutron
# python train.py -i /data/suehara/mldata/pfa/murata/neutron_1to100GeV/train -ii /data/suehara/mldata/pfa/murata/neutron_1to100GeV/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 100 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 1e-4 --lr-policy cosineReduce --clip-value 10 --ddp > log/energy_regression/tc_neutron_1to100GeV_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
# python train.py -i /data/suehara/mldata/pfa/murata/neutron_1to100GeV/train -ii /data/suehara/mldata/pfa/murata/neutron_1to100GeV/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 100 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --LE-track ${alphbeta} --energy-regression-weight --momentum --momentum-amp --qmin 0.2 --learning-rate 1e-4 --lr-policy cosineReduce --clip-value 10 --ddp > log/energy_regression/weighted_edep/tc_neutron_1to100GeV_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
## neutron fintuning
# ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2025_09_30_105247_outputD5/ckpt_499_1.pth.tar
# python train.py -i /data/suehara/mldata/pfa/murata/neutron_1to100GeV/train -ii /data/suehara/mldata/pfa/murata/neutron_1to100GeV/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 100 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 2e-5 --lr-policy cosineReduce --clip-value 10 --ddp --model-ckpt ${ckpt} > log/energy_regression/tc_neutron_1to100GeV_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log

## fine tuning using nnqq, neutron, gamma, kaon samples
# ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2025_09_30_105247_outputD5/ckpt_499_1.pth.tar
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/mixed/train/less_sample/eventCut/eventCut -ii /data/suehara/mldata/pfa/murata/data/tc/mixed/validation/less_sample/eventCut/eventCut --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 20 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 2e-5 --lr-policy cosineReduce --clip-value 10 --ddp --model-ckpt ${ckpt} --epochs-nobeta -1 --epochs-noLE -1 > log/energy_regression/tc_mixed_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
ckpt=checkpoint/energy_regression/ckpts_gravnet_new02_2026_03_18_163427_outputD5/ckpt_429_1.pth.tar
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/mix/train -ii /data/suehara/mldata/pfa/murata/data/tc/mix/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 32 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 1e-5 --lr-policy cosineReduce --clip-value 10 --ddp --gpus 4,5,6,7 --model-ckpt ${ckpt} --epochs-nobeta -1 --epochs-noLE -1 --nrestart-cosreduce 1 --ilc-sharded --ilc-file-cache 16 > log/energy_regression/tc_mixed_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/mix/train -ii /data/suehara/mldata/pfa/murata/data/tc/mix/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 32 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --qmin 0.2 --learning-rate 2e-5 --lr-policy cosineReduce --clip-value 10 --ddp --model-ckpt ${ckpt} --epochs-nobeta -1 --epochs-noLE -1 --nrestart-cosreduce 1 --ilc-sharded --ilc-file-cache 16 > log/energy_regression/tc_mixed_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}.log




outputD=5
ncuda=1
alphbeta=alpha_tracker_diff_log_perCluster     # alpha_tracker   alpha_tracker_diff_log
sumdis=sum_log_perCluster                      # sum_log         sum_log_perCluster
batch_size=40
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 40 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --qmin 0.2 --learning-rate 5e-4 --lr-policy cosineReduce --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp --regression-coefficinet 0.1 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# echo python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size ${batch_size} --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --qmin 0.2 --learning-rate 5e-4 --lr-policy cosineReduce --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp --regression-coefficinet 0.1 --clip-value 10 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size ${batch_size} --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --qmin 0.2 --learning-rate 5e-4 --lr-policy cosineReduce --energy-regression --LE-track ${alphbeta} --momentum --momentum-amp --regression-coefficinet 0.1 --clip-value 10 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/data/tc/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size ${batch_size} --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --qmin 0.2 --learning-rate 5e-4 --lr-policy cosineReduce --energy-regression --energy-regression-cluster --LE-track ${alphbeta} --LE-cluster ${sumdis} --momentum --momentum-amp --clip-value 10 > log/energy_regression/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}_${alphbeta}_momentum.log


## no energy regression 
outputD=5
ncuda=0
alphbeta=alpha
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 40 --output-dimension ${outputD} --ckptdir checkpoint/no_energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --qmin 0.1 --learning-rate 5e-4 --lr-policy cosineReduce > log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log
# python train.py -i /data/suehara/mldata/pfa/murata/data/ntau_10GeV_10/train -ii /data/suehara/mldata/pfa/murata/data/ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 40 --output-dimension ${outputD} --ckptdir checkpoint/no_energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --learning-rate 3.0e-5 --min-lr 2.5e-6 --ddp > log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log
# python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 50 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --ReduceLROnPlateau --energy-regression --momentum --momentum-amp --LE-track ${alphbeta} > log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log
# echo "python train.py -i /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/train -ii /data/suehara/gravnet_ilc/data/ntau/tc_ntau_10GeV_10/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 50 --output-dimension ${outputD} --ckptdir checkpoint/energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --ReduceLROnPlateau --energy-regression --momentum --momentum-amp --LE-track ${alphbeta} > log/tc_ntau_10GeV_10_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log"

# all di-jet samples (nnqq and fixed jets)
outputD=5
ncuda=1
python train.py -i /data/suehara/mldata/pfa/murata/data/tc/all_dijets/train -ii /data/suehara/mldata/pfa/murata/data/tc/all_dijets/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 32 --output-dimension ${outputD} --ckptdir checkpoint/no_energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --momentum --momentum-amp --qmin 0.2 --learning-rate 2e-5 --lr-policy cosineReduce --clip-value 10
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/all_dijets/code_test/train -ii /data/suehara/mldata/pfa/murata/data/tc/all_dijets/code_test/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 32 --output-dimension ${outputD} --ckptdir checkpoint/no_energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --momentum --momentum-amp --qmin 0.2 --learning-rate 2e-5 --lr-policy cosineReduce --clip-value 10 --ddp
# python train.py -i /data/suehara/mldata/pfa/murata/data/tc/all_dijets/train -ii /data/suehara/mldata/pfa/murata/data/tc/all_dijets/validation --no-split --thetaphi --cuda cuda:${ncuda} --epochs 500 --beta-track --force-track-alpha --batch-size 32 --output-dimension ${outputD} --ckptdir checkpoint/no_energy_regression/ckpts_gravnet_new02_${DATE}_outputD${outputD} --momentum --momentum-amp --qmin 0.2 --learning-rate 2e-5 --lr-policy cosineReduce --clip-value 10 --ddp --gpus 0,1,3,4 --model-ckpt ${ckpt} --ilc-sharded --ilc-cache-ram-fraction 0.8 > log/no_energy_regression/all_dijets/tc_mixed_timingcut_forcealpha_thetaphi_outputD${outputD}_${DATE}.log
